name: Build and Test .NET

on:
  pull_request_target:

jobs:
  build-and-test:
    name: Run Shared Build and Test Workflow
    uses: IntelliTect-Samples/EWU-CSCD371-2024-Winter/.github/workflows/build-and-test.yml@BMichaelis/TestMain
    with:
      check-formatting: false
      dotnet-build-enforce-code-style: false
      add-editorconfig: false
      add-analyzers: false
      enable-net-analyzers: false
      enable-nullability: false